# cfg file
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/task-manager_db
#    username: admin
#    password: pass
#    driver-class-name: org.postgresql.Driver


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/task-manager